name: Check for dependencies

on:
  schedule:
  - cron: "0 8 * * 3"

  push:
    paths:
      - .github/workflows/versions.yml
      - provision/pkglist
      - tools/upgrade.bash

jobs:
  apt-get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Review and upgrade the dependencies
        uses: docker://cardboardci/ci-core:privileged
        with:
          args: "tools/upgrade.bash"
      - name: Commit the dependency changes
        uses: cardboardci/github-actions/auto-commit@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: '/pkglist'
          MESSAGE: 'Upgrade packages to latest apt-get dependencies'
          PULL_REQUEST_TITLE: 'Bump image dependencies to latest'